const express = require('express')
const router = express.Router()
const userHandler = require('../router_handler/user')
const blogHandler = require('../router_handler/blogPublic')
const blogArticleHandler = require('../router_handler/blogArticle')
router.post('/admin/login',userHandler.loginFn)
router.post('/admin/register',userHandler.regFn)
router.post('/login',userHandler.loginWebFn)
router.post('/register',userHandler.regWebFn)
router.post('/exit',userHandler.exitLoginWeb)
router.post('/updateuser',userHandler.updateUser)

router.post('/userinfo',userHandler.userInfo)
router.post('/messageboard',userHandler.msgBoard)
router.post('/delmsgboard',userHandler.delMsgBoard)
router.post('/getmsgboard',userHandler.getMsgBoardData)
router.post('/replyMsg',userHandler.replyMsg)
router.post('/getreplymsgdata',userHandler.getReplyMsgData)

router.post('/photowall',blogHandler.reqPhotos)
router.post('/photowalldel',blogHandler.delPhoto)

router.post('/writeblog',blogArticleHandler.writeBlogs)
router.post('/addclassify',blogArticleHandler.addClassify)
router.post('/getclassifylist',blogArticleHandler.getClassifyList)
router.post('/delclassify',blogArticleHandler.delClassify)
router.post('/updclassify',blogArticleHandler.updClassify)
router.get('/getarticlelist',blogArticleHandler.getArticleList)
router.post('/delarticle',blogArticleHandler.delArticle)
router.post('/updatearticle',blogArticleHandler.updArticle)
module.exports = router